### PR TITLE
Update to v0.1.0-beta.8.1

### PR DESCRIPTION
**Pull request by sampoyigi**
Renamed bootstrap.php to extend.php
Restructure js files
Replaced deprecated classes

### CODE REVIEW

**Comment by fabwu** [comment]
Thanks for your help. I have my exams in a couple of weeks so I won't have time to review this but I'll merge it asap.

**Comment by sampoyigi** [comment]
No problem. Happy to help.

**Comment by gerbz** [comment]
I was coming to report the same issue - glad to see there's already a PR submitted :) - nice work @sampoyigi

**Comment by gerbz** [comment]
@fabwu any chance you have some time to take a look? :)

**Comment by fabwu** [comment]
@gerbz Nope sorry. I have my last exam on the 1st of February after that I'll have a look or if you can confirm me that everything works as expected I can merge the PR now.

**Comment by gerbz** [comment]
@fabwu I dont know how to download a version of the code with the changes - if you can point me towards that I can test it out

**Comment by sampoyigi** [comment]
@gerbz, you can download from here https://github.com/sampoyigi/flarum-ext-sso

**Comment by gerbz** [comment]
Thanks guys - got it up and running using the wordpress plugin too - all looks good!

**Pull request merged**
