### PR TITLE
Added new functions to reset password

### PR DESCRIPTION
**Pull request by dkaitou**
Code on successful login:

$forum = new Forum();
$forum->resetPassword(strtolower(str_replace(' ', '', $member_strforumusername)), $member_strforumhash  );
$forum->login( strtolower(str_replace(' ', '', $member_strforumusername)) , $stremail, $member_strforumhash);

### CODE REVIEW

**Review by fabwu — CHANGES_REQUESTED** [review]
Could you please fix the code formatting?

Please don't change any whitespace and just add your new feature.

**Comment by dkaitou** [comment]
Hi @fabwu  

Sorry, this is my first folk and commit to github. I will clean that up and let you know soon.

**Comment by dkaitou** [comment]
Hi @fabwu 

I have grabbed original file "Forum.php" from your master branch. And put in my new functions. 

But the diff of the changed "Forum.php" really confused me. 

Sorry if that is still not right and I can update this pull request if that still needs adjustments.

**Review by fabwu — CHANGES_REQUESTED** [review]
No worries I did the same mistake on my first PR. 

Unfortunately it's still not ok. Make sure you take the same file and just touch the lines which are affected from your change and leave the others as they are.

**Comment by dkaitou** [comment]
Hi @fabwu 

Sorry about taking that long.  Here is the newest version without strange new lines. 
Please let me know if there are any other problems.

**Comment by fabwu** [comment]
There were a lot of API changes since the last update so this won't work with the new version.

**Pull request closed without merging**
